### ISSUE TITLE
Password caching does not work when connecting to session 

### ISSUE THREAD

**Issue by JJK96** [occivink/kakoune-sudo-write#1]
When connecting to a session from a different terminal it does not work, connecting to a session from the same terminal does work however.

### Steps to reproduce

```sh
sudo touch testfile
kak -s test -d
```
Close the terminal.
Then in a new terminal
```sh
kak -c test testfile
```
Then do `:sudo-write<ret>`

### Result

> Something went wrong

I retrieved some more debug info and `sudo -n` fails with: 
> a password is required

### Expected result

Writes to file

**Comment by occivink** [comment]
That particular combination (server/client plus different terminals) seems to work on my end. I don't know exactly by which mechanism password caching works with sudo, but since all calls to `sudo` are executed on the server so I think it should work?
Unfortunately `sudo` is a rather inscrutable program, it has a lot of options that are weirdly incompatible with one-another and doesn't output any kind of error when that happens.
Maybe you can try replacing `sudo -n -- dd if="$kak_main_reg_f" of="$kak_buffile" >/dev/null 2>&1` with `sudo -n -- true` to see if it's sudo or dd that is failing?

**Comment by JJK96** [comment]
I just tried to follow my own steps again, it seems that you need to close the original terminal (the one where the server was started) to reproduce the issue.
